export const deportes = [
  { name: "Adventure", url: "https://i.postimg.cc/5NqBDZNC/Adventure.png" },
  {
    name: "American Football",
    url: "https://i.postimg.cc/qvJsrjzZ/American-Football.png",
  },
  { name: "Baseball", url: "https://i.postimg.cc/qv18vyKB/Baseball.png" },
  { name: "Basketball", url: "https://i.postimg.cc/7LbSGh13/Basketball.png" },
  { name: "Bicycle", url: "https://i.postimg.cc/gJZRs7Tr/Bicycle.png" },
  { name: "Fishing", url: "https://i.postimg.cc/15HFvwJ0/Fishing.png" },
  { name: "Fitness", url: "https://i.postimg.cc/zvwhZg5r/Fitness.png" },
  { name: "Football", url: "https://i.postimg.cc/Wp0gJQZH/Football.png" },
  { name: "Hiking", url: "https://i.postimg.cc/02xmGcd2/Hiking.png" },
  { name: "Hockey", url: "https://i.postimg.cc/QddTwCy2/Hockey.png" },
  { name: "Jogging", url: "https://i.postimg.cc/TPyW2SGQ/Jogging.png" },
  { name: "Surfing", url: "https://i.postimg.cc/QdYT3sLH/Surfing.png" },
  { name: "Target", url: "https://i.postimg.cc/43rHY5xG/Target.png" },
  { name: "Tennis", url: "https://i.postimg.cc/Y9YGYWvW/Tennis.png" },
  { name: "Yoga", url: "https://i.postimg.cc/zvNLjGhP/Yoga.png" },
  { name: "Golf", url: "https://i.postimg.cc/ZRXktWHV/Golf.png" },
  { name: "Adventure", url: "https://i.postimg.cc/5NqBDZNC/Adventure.png" },
  {
    name: "American Football",
    url: "https://i.postimg.cc/qvJsrjzZ/American-Football.png",
  },
  { name: "Baseball", url: "https://i.postimg.cc/qv18vyKB/Baseball.png" },
  { name: "Basketball", url: "https://i.postimg.cc/7LbSGh13/Basketball.png" },
  { name: "Bicycle", url: "https://i.postimg.cc/gJZRs7Tr/Bicycle.png" },
  { name: "Fishing", url: "https://i.postimg.cc/15HFvwJ0/Fishing.png" },
  { name: "Fitness", url: "https://i.postimg.cc/zvwhZg5r/Fitness.png" },
  { name: "Football", url: "https://i.postimg.cc/Wp0gJQZH/Football.png" },
  { name: "Hiking", url: "https://i.postimg.cc/02xmGcd2/Hiking.png" },
  { name: "Hockey", url: "https://i.postimg.cc/QddTwCy2/Hockey.png" },
  { name: "Jogging", url: "https://i.postimg.cc/TPyW2SGQ/Jogging.png" },
  { name: "Surfing", url: "https://i.postimg.cc/QdYT3sLH/Surfing.png" },
  { name: "Target", url: "https://i.postimg.cc/43rHY5xG/Target.png" },
  { name: "Tennis", url: "https://i.postimg.cc/Y9YGYWvW/Tennis.png" },
  { name: "Yoga", url: "https://i.postimg.cc/zvNLjGhP/Yoga.png" },
  { name: "Golf", url: "https://i.postimg.cc/ZRXktWHV/Golf.png" },
];
